spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
#  webflux:
#    base-path: /api
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    ssl: false
    timeout: 15000
    lettuce:
      shutdown-timeout: 200
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 8s
  data:
    redis:
      repositories:
        enabled: false

expiration:
  minute:
    accesstoken: 1440
    refreshtoken: 43200

datasource:
  username: admin
  password: admin1234
  host: localhost
  port: 3306
  database: auth
  pool:
    maxIdleTime:
    maxCreateConnectionTime:
    initSize:
    maxSize:

jasypt.encryptor:
  password: Authq1w2#!
